# Generated by Django 5.0.6 on 2024-07-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_student2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prfile_image',
            new_name='profile_image',
        ),
    ]
