# Generated by Django 5.0.6 on 2024-07-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeFaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('college_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('bio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
