# Generated by Django 5.0.6 on 2024-07-29 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_collegefaker_studentfaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfaker',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.collegefaker'),
        ),
    ]
