# Generated by Django 5.0.6 on 2024-07-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_studentfaker_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfaker',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
