# Generated by Django 5.0.6 on 2024-08-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_product_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('skill', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
