# Generated by Django 5.0.6 on 2024-08-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
