# Generated by Django 5.0.6 on 2024-08-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('price',)},
        ),
    ]
