# Generated by Django 5.0.6 on 2024-08-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('price', 'book_name')},
        ),
    ]
