# Generated by Django 5.0.6 on 2024-08-05 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_book_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('brand_name', 'country')},
        ),
    ]
