# Generated by Django 5.0.6 on 2024-08-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_engineer_hr_investors'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student2',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='age_gte_18'),
        ),
    ]
