# Generated by Django 5.0.6 on 2024-08-05 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateField(auto_created=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
            options={
                'ordering': ('description',),
            },
        ),
    ]
