# Generated by Django 5.0.6 on 2024-08-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdbnews',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
